allowBuilds:
  esbuild: true
  msgpackr-extract: true
  simple-git-hooks: true
minimumReleaseAgeExclude:
  - '@sledge-pdm/*'
onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - msgpackr-extract
  - simple-git-hooks
