[package]
name = "sledge-wasm"
version = "0.1.0"
authors = ["innsbluck <innsbluck@gmail.com>"]
description = "wasm module for sledge"
license = "MIT/Apache-2.0"
edition = "2021"

[package.metadata.wasm-pack.output]
name = "@sledge/wasm"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.104"
