name: development-release

on:
  push:
    tags: ['v*.*.*-dev.*']
  workflow_dispatch: {}

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target universal-apple-darwin'
          - platform: 'ubuntu-22.04' # for Tauri v1 you could replace this with ubuntu-20.04.
            args: ''
          - platform: 'windows-latest'
            args: ''
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup pnpm (install first for node cache detection)
        uses: pnpm/action-setup@v4
        with:
          version: 10.16.1
          run_install: false

      # Node & Rust 環境セットアップ
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
      - uses: pnpm/action-setup@v4

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install x86_64-apple-darwin binary (macOS only)
        if: matrix.platform == 'macos-latest'
        run: |
          rustup target add x86_64-apple-darwin

      - name: Cache Rust build
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            apps/sledge/src-tauri
            packages/wasm

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: build wasm
        run: pnpm wasm:build

      - name: install frontend dependencies
        run: pnpm install

      # Tauri Build + Release Upload
      - uses: tauri-apps/tauri-action@v0
        id: tauri-build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'Development Build ${{ github.ref_name }}'
          releaseBody: 'This is a development build. Use at your own risk.'
          releaseDraft: false # Don't care because it's a dev build
          prerelease: true
          projectPath: './apps/sledge'
          includeUpdaterJson: true
          updaterJsonPreferNsis: true
          updaterJsonKeepUniversal: true
          args: ${{ matrix.args }}

      - name: Upload dev artifacts
        uses: actions/upload-artifact@v4
        if: matrix.platform == 'ubuntu-22.04'
        with:
          name: binaries-linux
          path: |
            ${{ github.workspace }}/apps/sledge/src-tauri/target/release/bundle/**/*.deb
            ${{ github.workspace }}/apps/sledge/src-tauri/target/release/bundle/**/*.rpm

      - name: Upload dev artifacts
        uses: actions/upload-artifact@v4
        if: matrix.platform == 'macos-latest'
        with:
          name: binaries-macos
          path: |
            ${{ github.workspace }}/apps/sledge/src-tauri/target/universal-apple-darwin/release/bundle/**/*.dmg
            ${{ github.workspace }}/apps/sledge/src-tauri/target/universal-apple-darwin/release/bundle/**/*.app

      - name: Upload dev artifacts
        uses: actions/upload-artifact@v4
        if: matrix.platform == 'windows-latest'
        with:
          name: binaries-windows
          path: |
            ${{ github.workspace }}/apps/sledge/src-tauri/target/release/bundle/**/*.exe
